# https://myriad-dreamin.github.io/tinymist/frontend/helix.html
[language-server.tinymist]
command = "tinymist"
# Open preview with `tinymist preview slides.typ`
config = { preview.background.enabled = true, preview.background.args = [
    "--data-plane-host=127.0.0.1:23635",
    "--open",
] }

[[language]]
language-servers = ["tinymist"]
name = "typst"
